services:
    blog_api:
        build: .
        ports:
            - 5000:5000
        volumes:
            - .:/blog_api
        depends_on:
            blog_db:
                condition: service_healthy
                
    blog_db:
        container_name: database
        image: postgres:17
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: blog
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}